### ISSUE TITLE
Return JavaScript Objects in Event Handlers

### ISSUE THREAD

**Issue by antletem** [s-cork/Tabulator#15]
Currently the event handlers return a dictionary of the row data instead of the actual row/cell object. It would be useful, to also return the object itself instead of the data. This  would allow the user to use that objects methods/attributes and still get the row data if wanted.

**Comment by s-cork** [comment]
Did you want to submit a PR for this?

The only question is what should the parameters be named.
Maybe `_row` and `_cell`. 
I'm open.

**Comment by antletem** [comment]
Yeah, forked the repo and working on a branch right now. 

I was thinking of just returning ```row`` and ```cell`` how you have it now and not return the dictionary at all, but I am not opposed to your suggestion.

Is there a standard for returning ```_row```? I only ask because I am trying to learn. :)

Thoughts?

**Comment by s-cork** [comment]
You shouldn't break code that exists. This codebase predates the JavaScript objects being allowed in python and that's why row is always a dictionary. 

If you replace row with the JavaScript row instead, then you'll break code out there that already uses these callbacks. 

If there is no name conflict with existing parameters then we can use the names as they are. 

I'm suggesting using the single underscore to not conflict with the current names (sometimes a single underscore is used for that purpose but it's usually trailing). And to signal these objects are a bit different (they're JavaScript wrapped objects). There's no real convention for that. The leading underscore does signal that these objects are either private, or to be used and your own risk. 


I'm not opposed to making a breaking change to use JavaScript wrappers instead of python objects. But that would need to be a version bump using anvils new dependency versioning. 

I am planning on a rewrite of the library soon since tabulator have also done a rewrite of their own. And it would be nice to update the tabulator version to the latest one. That seems to be the best time to make breaking changes.

**Comment by antletem** [comment]
It seems so obvious when you explain it! Thank you for teaching.

And understood,  I am -7 UTC .
