### ISSUE TITLE
get_selected_data() not working

### ISSUE THREAD

**Issue by antletem** [s-cork/Tabulator#21]
**Describe the bug**
I am trying to get all of the selected rows of a table using the ```self.tabulator.get_selected_data()``` attribute. I have also trying ```self.tabulator.get_selected()``` as that is the auto-complete suggestion.

I get the following error:

'tabulator' object has no attribute 'get_selected_data'

for both instances.

**To Reproduce**
I create a table setting selectable option to True. I know it was recognized because I also change the layout successfully and the row does highlight on selection.

On the row selected method I call the ```self.tabulator.get_selected_data()``` method, but it does not return the selected row.

This is on the Tabulator-5 development code.

**Comment by s-cork** [comment]
When do you call this method?
Methods can only be called after the table is built.
I use that in the example app for the delete button click and it's working there.

I think it points to a separate issue about maybe throwing a RuntimeError if trying to access a method before the table is ready.
Note this is new behaviour because I used to be able to create the tabulator component before the form show
Now it has to be created after form show

**Comment by antletem** [comment]
It is used after the table is create. I'll look at the example and report back.

Thanks!

**Comment by s-cork** [comment]
this might be related to the accidental push earlier
`get_selected` would only have been in the autocomplete for the current published branch

**Comment by s-cork** [comment]
Assuming this is fixed - if not please re-open
