### ISSUE TITLE
Loading App Tables in options issue

### ISSUE THREAD

**Issue by expressintegrations** [s-cork/Tabulator#28]
Hey I am trying to leverage the native function to pass an app table as the data to the Tabulator but I keep getting no rows to display.

Here is a clone link: https://anvil.works/build#clone:OYM2GBKFNX5XXE3R=YWZGVWTUR43NVMA5P2H53QPE|TGQCF3WT6FVL2EM2=

I define my tabulator under the init as 
```
    self.tabulator_1.columns = [
      {"title": "Name", "field": "name"},
      {"title": "Status", "field": "status"},
      {"title": "Error", "field": "error"},
    ]
    self.tabulator_1.options = {
      "app_table": anvil.server.call('get_data'),
      "data_loader": False, # display JS Tabulators 'loading' component
      "loading_indicator": False # defaults to True - whether to use the anvil spinner during page loading
    }
```
And my server call as 
```
@anvil.server.callable
def get_data():
  return app_tables.table_1.client_readable()
```
And the result:

![image](https://user-images.githubusercontent.com/87839988/160693202-c85f0162-a7be-4f79-af3c-e79112ca9a26.png)

**Comment by s-cork** [comment]
Just to check the obvious - which version of tabulator are you using?

If it's 1.x or Production, that feature won't exist. 
Make sure you're on 2.x or Development.

**Comment by s-cork** [comment]
@expressintegrations I've checked the clone and it's pinned to the Published version so that won't work. The Published version still points to Tabulator 1.x so as to not break peoples code and give them a chance to migrate. There's a warning message in the output about the impending switch. 

I'll add another one whenever someone tries to set the options property. 

You'll also need to have a valid unique id column in your table. You can set which column using the index property in the design view or by changing the tabulator options and defining an index property there.

**Comment by expressintegrations** [comment]
Just checked the version. Switching to a 2.x did the trick, thanks so much! Is it possible to just use the auto-generated anvil row IDs from app tables as the index?

**Comment by s-cork** [comment]
I thought about it.

I could add an api in the options but probably not by default. Because the index needs to be included in the data passed to tabulator so that I can cache the row and also retrieve the row from the data. 

Like
```
self.tabulator.options = {
   ...
   "use_row_id": True
}

```

Thoughts?

**Comment by expressintegrations** [comment]
So essentially you would be calling `row.get_id()` on each row before loading the table? Think that would have a significant impact on performance for lots of data?

**Comment by expressintegrations** [comment]
There is a chance that this may get confusing if you use the index property in addition to the `use_row_id`

**Comment by s-cork** [comment]
There's a fast path in anvil that doesn't require a round trip and is as quick as a dictionary look up - so yes but no. 

```python
anvil._get_live_object_id(row)
```

**Comment by s-cork** [comment]
Yes it would which is why if you use that flag then it would override the index property. 

So you'd only set that if you didn't have a unique id column in your table. 

You can't exclude index because it's required by Tabulator. Tabulator uses that property for almost all row lookups. Eg updating a row's data will require the index as part of the data.

**Comment by expressintegrations** [comment]
Yeah I just meant that you would automatically set the index property to the row ID in the background if someone uses an app table as a data source

**Comment by expressintegrations** [comment]
Another comment while I have you. On the built in `row_selection_column`, it does not allow me to select multiple rows:
https://www.loom.com/share/fc16cd1bea8245c687e0d34a80d3f744

**Comment by s-cork** [comment]
Set selectable: highlight in the options. I'll switch that on if the column is included as part of the definition

**Comment by expressintegrations** [comment]
Perfect, much appreciated!

**Comment by expressintegrations** [comment]
Ok one more on app table usage. When using app table rows, the columns from the underlying table are lost when the row is converted to a proxy object. Any way we can keep that?

**Comment by s-cork** [comment]
there already is - in the docs - `row.get_table_row()` or `self.tabulator.get_table_rows('visible')`

**Comment by expressintegrations** [comment]
Ahh! Sorry I missed that in my initial run through of the docs
