### ISSUE TITLE
Date column with headerFilter makes tabulator fail

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#36]
With th dev version of Tabulator I have a date column, defined like this:
```
      {'title':"Start", 'field':"start_date", 'headerFilter': False, 
         "formatter": "date", "sorter": "date", "formatter_params": {"format": "iso", "tz": None}},
```
This works fine. However when I set headerFilter to True, tabulator is empty and column header from the date column and beyond are not drawn. No error is displayed.

**Comment by s-cork** [comment]
What happens when you set header filter to `"date"` instead?

**Comment by s-cork** [comment]
I've looked into this and have updated dev branch so you can test it `header_filter_func`

Stick with your code but add the following

```python
def date_header_filter(val, row_val, row_data, **params):
    return val in str(row_val)

self.tabulator.columns = [
    ...
    {'title':"Start", 'field':"start_date", 'headerFilter': True, 
         "formatter": "date", "sorter": "date", "formatter_params": {"format": "iso", "tz": None}
     "header_filter_func": date_header_filter},
    ]

**Comment by mjmare** [comment]
Hmm, the table shows normally now, even with my own old code. I presume setting the app dependency to "development" always uses the latest version from GitHub?
With your code, the table shows as normal, but the header_filter_func seems not to be called. In fact whatever the setting for headerFilter, the table looks like this:
<img width="538" alt="Screenshot 2022-04-14 at 10 24 05" src="https://user-images.githubusercontent.com/1711378/163345475-cb8787fc-5eff-4be1-a439-a471efb73a7e.png">

PS sorting works.

**Comment by s-cork** [comment]
Did you keep the header_filter as True? If you changed it to `"date"` it won't work. 

Yeah development is always the latest version.

**Comment by mjmare** [comment]
I just checked to make sure. headerFilter is set to True. 
I put a print statement in the filter function and nothing get printed to the console.

**Comment by s-cork** [comment]
I edited the post. Since I have this working on the development branch. Please provide a clone link that demonstrates the issue. 

You can also try setting the headerFilter to `"input"`.

**Comment by s-cork** [comment]
Ps here's the example of it working. https://dev-example-tabulator.anvil.app

**Comment by mjmare** [comment]
"input" works, True doesn't.
With "input" the function _is_ called. The filtering process is quite slow.
With "input" without filter function the input box is shown, but filtering does not work.

**Comment by s-cork** [comment]
Like I said - tabulator is comparing a string to a date which is why it won't work without the `header_filter_func`.

Before we think about performance what do you actually want the behaviour to be for a date header filter here?
I can't see that a text string input being a good conduit for a filtering a date column?

I can make the anvil datepicker work here (it currently won't) but is that behaviour we want?
Using a datepicker you'd be looking for equality matching on a date column.

**Comment by mjmare** [comment]
> Like I said - tabulator is comparing a string to a date which is why it won't work without the `header_filter_func`.

OK
> 
> Before we think about performance what do you actually want the behaviour to be for a date header filter here? I can't see that a text string input being a good conduit for a filtering a date column?
> 
> I can make the anvil datepicker work here (it currently won't) but is that behaviour we want? Using a datepicker you'd be looking for equality matching on a date column.

String filtering is better than a date picker in some cases. With string I can search for specific years or months or days. A Datepicker looks nicer but only supports, as you said, equality checking.

**Comment by s-cork** [comment]
### Performance:
_How many rows are we filtering against?_

**Something you can try:**
Eliminate the python javascript dance as the bottleneck:
- create a `str_date` column, which will just be your date column but converting each date using `.isoformat()` in advance.

use the column definition:
```python
self.tabulator.columns = [
    ...
    {'title':"StartAlt", 'field':"str_date", 'header_filter': True, "header_filter_func": "like"},
    ]

```

The above will do a filter but directly on javascript strings.

If it doesn't solve the performance issue - then there's probably not much we can do about it, since this will use the builtin tabulator filtering.


If that solves the performance issue:
A. consider using the iso formatted dates instead.
B. Alternatively create a dummy column with the already converted string and use that in the `header_filter_func`

```python
def header_filter_func(val, row_val, row_data, **params):
    return val in row_data.str_date
```


---

I would also consider using a between header filter with two datepickers.
But UI wise it'd probably be a non starter as a header filter element.

**Comment by s-cork** [comment]
fyi - if you did want to have a look at having a header filter component that supported dates between x and y, the following should now work.

(You can see proof of concept at https://dev-example-tabulator.anvil.app/ )

```python
# BetweenPicker is a Blank Panel Form with two DatePicker components
# the date_change event is the change handler for both pickers

from datetime import date

class BetweenPicker(BetweenPickerTemplate):
    ...
    def date_change(self, **event_args):
        """This method is called when the selected date changes"""
        d1 = self.date_picker_1.date
        d2 = self.date_picker_2.date
        if d1 is None and d2 is None:
            self.raise_event("x-cancel")
        else:
            self.raise_event("x-success", value=(d1 or date.min, d2 or date.max))

```

```python
def date_header_filter(val, row_val, row_data, **filter_params):
        return val[0] <= row_val <= val[1]

# Tabulator Column 
self.tabulator_1.columns = [
    ...
            {
                "title": "Date Of Birth",
                "field": "dob",
                "sorter": "date",
                "formatter": "date",
                "formatter_params": {"format": "%d/%m/%Y"},
                "header_filter": BetweenPicker,
                "header_filter_func": date_header_filter,
            },
]
```

**Comment by mjmare** [comment]
A bit too intrusive IMO (but I realise it is a proof of concept). I think I'll stick to string filtering for the moment.
