### ISSUE TITLE
Error finding row after changing default index

### ISSUE THREAD

**Issue by benlawraus** [s-cork/Tabulator#47]
**Describe the bug**
After changing default index to unique string, can no longer ascertain row:

```
     Tabulator.default_options['index']='uid'

      self.tabulator.data = [{'uid':'1','name':'Fred','email':'fred@email.com','phone':'123'},
                            {'uid':'10','name':'Fromble','email':'fromble@email.com','phone':'345'},
                            {'uid':'100','name':'Freud','email':'freud@email.com','phone':'567'},
                            {'uid':'1000','name':'Frank','email':'frank@email.com','phone':'789'},]
    :
    :
    self.tabulator.delete_row(data["uid"])

ExternalError: Delete Error - No matching row found
at StuCorkForm, line 108
  called from StuCorkForm, line 117
  called from Tabulator, line 147

```

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Go to https://anvil.works/build#clone:N5XSFX4DQ6Q7SFGE=7IDQ7KL3DKG6ZKLJPPAM3CIY
2. Click on RUN
3. Click on Trash Can in row

**Expected behavior**
Delete row

**Comment by s-cork** [comment]
I don't think default options work for properties you can set in the designer.

You'll have to set the index property per tabulator component - either in the designer or in the options attribute. 

I reckon if you print `self.tabulator_1.index` it'll be `"id"`. 

I'll either document this or have a think about how to make it work.  

The designer index property feels quite important since without it basic tabulator functions don't work.

**Comment by s-cork** [comment]
Looks like I already documented this in https://github.com/s-cork/Tabulator#default-options
See the last sentence:
> Note that default_options will not override any designer propeties. e.g. setting Tabulator.default_options["header_visible"] = False will have no effect.



the solution is to either:
- set the index in the designer
- set the index before instantiation in code `self.tabulator_1.index = "uid"`
- set the index in the options property `self.tabulator.options["index"] = "uid"`
