### ISSUE TITLE
Possible regression (functions as formatters)

### ISSUE THREAD

**Issue by Starwort** [s-cork/Tabulator#5]
I noticed my code is now throwing a `TypeError: <lambda>() takes 1 positional argument but 3 were  given`

I don't remember changing anything, but here's some debug information I did; after confirming how the formatter function is supposed to work (from issue #1) I believe this to be a regression

Relevant code:

```py
        self.tabulator.columns = [
            {
#                 "formatter": lambda *i, **kw: print(i, kw),
                "formatter": lambda row, **kw: row['expires'].strftime('%d/%m/%Y'), # row['expires'] is a datetime object
            ...
```

When using the first line instead of the second (to print debug information), every call prints `(<a (native JS) proxyobject>, {}, <proxyfunction 'e (native JS)'>) {}`

My assumption is that this is some regression; possibly some update to the native tabulator library caused this and some version of the anvil wrapper that I never upgraded to fixed this again; but I don't see it mentioned in the commit tree so I'm raising it here. Let me know if I've just done something stupid of course :upside_down_face:

**Comment by s-cork** [comment]
Yeap I added the asc bool as a 5th parameter to a custom sorter. 

Just a heads up. 

I basically rewrote the library when anvil.js.window got updated.

**Comment by Starwort** [comment]
Ahhh; I'll update soon then; perhaps there's a way of dynamically loading the latest version of the wrapper...

Anyway, that's thought for another issue

**Comment by s-cork** [comment]
When did you notice this issue btw?

I'm wondering when it popped up. Someone else reported it to me yesterday.

**Comment by s-cork** [comment]
ah I know what's happening here. There have been some updates to how javascript and python interact in anvil. Sending a callable from python to javascript now turns it into a javascript callable. And so Tabulator is just treating it as a javascript callable custom function. 

The default parameters for a custom javascript formatter are different to my implementation. Hence why we get 3 parameters instead of 1. 

Let me know how the update goes. 

I guess it's quite an advanced feature so not many people who use this dependency are probably using custom function formatters.

**Comment by Starwort** [comment]
> When did you notice this issue btw?
> 
> I'm wondering when it popped up. 

At least a week ago; but it could be longer
